### ISSUE TITLE
File paths not resolving correctly in extract_frames_ldm_ff++.py

### ISSUE THREAD

**Issue by angelaragonkifute** [megvii-research/CADDM#13]
In  [extract_frames_ldm_ff++.py](https://github.com/megvii-research/CADDM/blob/master/lib/extract_frames_ldm_ff%2B%2B.py) the default parameter for the variable NUM_FRAMES is 1. In this case there is no problem, in terms of corresponding frames, if only one frame is taken from each video, for a given fake video, its frame 0 will correspond perfectly with its source video frame 0. The problem comes when NUM_FRAMES is not 1. Let's consider NUM_FRAMES = 30. In this case, according to this code the frame index that will be taken will follow a linear distribution so if there are 300 frames and 30 frame are desired, frames 0,10,20,...,290,300 are taken. This is a problem since source videos and fake videos don't always have the same length so ifi 30 frames are desired for video fake A, frames 0,10,20,30,...300 are taken but if video source B has, for example 270 frames, then frames 0,9,18,27,37...270 will be taken. It is a small detail and to some extent is not even a problem because the frames will be very similar but the source paths are not entirely accurate.

**Comment by Leesoon1984** [comment]
> 
Same Problem, have you solved it?
