### ISSUE TITLE
cannot import name '_jpegpy' from 'lib.data_preprocess.utils.jpegpy'

### ISSUE THREAD

**Issue by xiaozhangxiaowen** [megvii-research/CADDM#16]
![image](https://github.com/megvii-research/CADDM/assets/84223525/1a005995-1d01-40a1-9b8c-77d8820bda9a)
# Hi，I have a question.can you help me, please?

**Comment by Kent1029** [comment]
You can refer to the following closed Issues.
["How do I generate so files"](https://github.com/megvii-research/CADDM/issues/7)
