### ISSUE TITLE
On the issue of poor training effectiveness

### ISSUE THREAD

**Issue by wang-qichang** [megvii-research/CADDM#17]
Hello, I tried to reproduce the training process. During the data preprocessing stage, I took one frame of a video every 10 frames and obtained 210000 photos. However, this result seems to be not as good. I spent a day training 15 epochs, but the accuracy remained between 0.75 and 0.85. Is it because I trained too little or something else? Does anyone have the same outcome as me?

**Comment by Nku-cs-dsc** [comment]
Hi, the proposed model needs training on the dataset with FST matching. (For more details refer to Explaining Deepfake Detection by Analysing Image Matching). Based on such datasets, the method reduces Implicit Identity Leakage by forcing the model to detect local artifact areas. If you want to train the model on your self-collection datasets, please check whether the dataset contains the FST matching.

**Comment by Gnonymous** [comment]
@wang-qichang Hi, I'm having the same problem as you, the dataset I'm using is ffpp, generated directly using the author's script, with only one frame taken from each video. The training results are the same as yours, please let me know if you have a new idea to solve this problem. Does ffpp comply with FST matching? Thanks for your question and answer.
