### ISSUE TITLE
about SBI

### ISSUE THREAD

**Issue by fubenzun** [megvii-research/CADDM#19]
I have a question，SBI AUC score is 93.18 in Celeb-DF dataset，Have you had a successful reproduction?I ran SBI official train code，only got 91.3。

**Comment by Nku-cs-dsc** [comment]
Hi, the SBI AUC score in our paper is quoted from the experiment part of the SBI paper. We conduct the comparative experiment based on adding the SBI augmentations in the data preprocessing method.

**Comment by fubenzun** [comment]
> Hi, the SBI AUC score in our paper is quoted from the experiment part of the SBI paper. We conduct the comparative experiment based on adding the SBI augmentations in the data preprocessing method.
HI.
Have you re-run the experiments in SBI by official code？I ran the code  only got 91.3 in CDF dataset,but the score in paper is 93.18?

**Comment by Nku-cs-dsc** [comment]
Sorry, we only reproduce SBI based on our code and never re-run the experiments with SBI official code.

**Comment by cygbbhx** [comment]
> Hi, the SBI AUC score in our paper is quoted from the experiment part of the SBI paper. We conduct the comparative experiment based on adding the SBI augmentations in the data preprocessing method.

Hi, I am trying to reproduce CADDM + SBI experiment and have a short question about "adding the SBI augmentations". 

1. Did you use the self-blending technique 1) before you do the multi-scale swapping? Or 2) afterwards? or 3) randomly do SBI besides global/local swap?

2. SBI uses only real images to generate own fake data. Did you also do so when running comparative experiments?
