### ISSUE TITLE
About FF++(c23 and c40). Can you provide AUC of frame level on c23 and c40? I note that these two compression rates seem to be more general results for comparison.

### ISSUE THREAD

**Issue by githuboflk** [megvii-research/CADDM#25]

**Comment by Nku-cs-dsc** [comment]
Hi, we have released the checkpoints of our model. You can test the model performance on the FF++(c23 & c40) directly~

**Comment by wqlcaq** [comment]
Frame-AUC of FF++ is 0.9513
Video-AUC of FF++ is 0.9513
the AUC on the FF++(c23)
