### ISSUE TITLE
no faces in 0:1.mp4

### ISSUE THREAD

**Issue by guotianli** [megvii-research/CADDM#32]
When generating a json file with my own data set,

height, width = frame.shape[:-1] # Gets the height and width of the image

AttributeError: 'NoneType' object has no attribute 'shape'. In fact, the size of the video that cannot get shape is the same as the size of the video that does not report error, which is 720✖1280

**Comment by Sun-researcher** [comment]
Senior, did you successfully reproduce CADDM, can you show me your conda virtual environment, please tell me about the process you run and need to change the program

**Comment by Nku-cs-dsc** [comment]
It seems that the type of frame is 'None' which means that your code failed to parse video frames from the input data. Please check the video format first, and make sure your video parse tools support such video format.
