### ISSUE TITLE
About set of train data

### ISSUE THREAD

**Issue by Gnonymous** [megvii-research/CADDM#37]
I would like to know how the data for the experimental training is set up, how many frames are taken from one video? For example, how many frames are taken for each of the 5 methods?(youtube, Deepfakes, FaceSwap...) As shown in the code of `extract_frames_ldm_ff++.py`, is it only one frame taken from each video? Thanks for your reply and work!

**Comment by Nku-cs-dsc** [comment]
We sample 32 frames in a video during the training phase.
