### ISSUE TITLE
Data set problem

### ISSUE THREAD

**Issue by Usriscedjdj** [megvii-research/CADDM#41]
My F ++ data set has been converted to a picture, how should I modify the code? When modifying the generated json file, is the json file used for training?

**Comment by Nku-cs-dsc** [comment]
Before training the model, you should extract face landmarks and store such meta information in the JSON file for face alignment during the data preprocessing phase.

**Comment by Usriscedjdj** [comment]
Thank you for your answer! Now I have encountered a new problem, after generating the json file, such an error is displayed, is there a problem with the generated file? Thank you so much!
![错误](https://github.com/megvii-research/CADDM/assets/96629668/0bb8449f-0bf1-42bd-a5d4-8fa856c76eb2)

**Comment by Nku-cs-dsc** [comment]
It seems that the image type is None, which means your script has not successfully read the image data. Please check your image read function to make sure your image path is correct.
